[http.middlewares.simpleAuth.basicAuth]
  users = ["admin:your_encrypted_password"]

[http.routers.api]
  rule = "Host(`proxy.treylabs.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
