version: '3.7'

# Note:
# This is just the latest version of a docker-compose.yml file I’ve done as of
# 2020-08-11. Update this when I learn better!
#
# You don’t want to actually run a production site exactly like this (at least
# with regards to the `command` using `runserver` like you would on your Mac).

networks:
  web:
    external: true
  internal:
    external: false

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      # HOST:CONTAINER
      - '8001:8001'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.backend=postgres-example_web_1
      - traefik.frontend.rule=Host:postgres.example.com
      - traefik.docker.network=web
      - traefik.port=8001
    networks:
      - internal
      - web
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.enable=false
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
