version: '3.7'

# Note:
# This is just the latest version of a docker-compose.yml file I’ve done as of
# 2020-09-08. Update this when I learn better!

networks:
  web:
    external: true
  internal:
    external: false

services:
  app:
    build: .
    command: gunicorn example_project.wsgi -b 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      # HOST:CONTAINER
      - '8001:8001'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.http.routers.app.rule=Host(`app.example.com`)
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=lets-encrypt
      - traefik.port=8001
    networks:
      - internal
      - web
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.enable=false
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
